baseURL = "https://colin.id"
languageCode = "en-us"
title = "Colin Burr"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true

[params]
  author = "Colin Burr"
  description = """
  In 💙 with the web. <br>
  Currently at Industry Dive. <br>
  Previously at Travelog, MyQVO, and SWPG at NCIFCRF.
  """
  publicationYear = "2020"

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    taxonomy = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    # name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/blog/"
    weight = 10

[[menu.main]]
    identifier = "twitter"
    # name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/_colinburr"
    weight = 20

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/sw3dish"
    weight = 30

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:hello@colin.id"
    weight = 40

[deployment]

[[deployment.targets]]
name = "colin.id"
URL = "s3://colin.id?region=us-east-1"
cloudFrontDistributionID = "ELCRHMT45IHA2"
